spring:

  session:
    store-type: redis

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: -1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: tae852852
